### ISSUE TITLE
Delay between the list and the button

### ISSUE THREAD

**Issue by Ricardo1980** [kizitonwose/CountryPickerView#142]
Hello,

When tapping a country in the list, the screen is dismissed and we see the previous screen. Then, after the previous screen is presented entirely, the flag is changed.

See this video:
https://user-images.githubusercontent.com/738681/116590537-c9cd1480-a915-11eb-9504-48ae28f1901c.MP4

Is there any way to remove this delay?

Thanks a lot.

**Comment by kizitonwose** [comment]
The "delay" happens because the delegate is called **after** the country list is dismissed. The fix would be to call it before dismissing the list.
However, this will likely break existing implementations that, for example, do some navigation after the country is selected and expects the list to have been dismissed.
Personally, I do not see the issue with it, but if you really want to change it, you'd have to fork the project and apply the change I suggested above.
