### ISSUE TITLE
set custom locale or change text

### ISSUE THREAD

**Issue by wellbranding** [kizitonwose/CountryPickerView#34]
How can I change locale with selection? User can select different languages in our app and we override strings. How can I also override default locale in countryPickerView? If that is impossible, how can I access strings of countryPickerView and set them myself? I need to change text of Back, search and Cancel

**Comment by kizitonwose** [comment]
Since version [2.2.1](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.1), the internal `UISearchController` is public for customisation purposes. You can access the `UISearchController` via the `CountryPickerViewController` which is provided in the `willShow` and `didShow` delegate methods. You should be able to change the `search` and `cancel` texts via the `UISearchController`.

For the `back` text, I believe that's handled by the navigation controller which can also be accessed via the `CountryPickerViewController`.
