### ISSUE TITLE
Search not working in real device but working on Simulator.

### ISSUE THREAD

**Issue by zykyan** [kizitonwose/CountryPickerView#41]

**Comment by kizitonwose** [comment]
I cannot replicate this. Can you try cleaning your build folder?
`Menu` -> `Product` -> `Clean Build Folder`

**Comment by zykyan** [comment]
Hey @kizitonwose sorry for getting back to you late, I tried cleaning build folder but still no luck
![img_0133](https://user-images.githubusercontent.com/15345370/54024361-ae47a280-41bf-11e9-8c95-aac3b96352c9.PNG)
![img_0134](https://user-images.githubusercontent.com/15345370/54024373-ba336480-41bf-11e9-9386-0a18efd07fb1.PNG)

**Comment by kizitonwose** [comment]
I can tell from your screenshots that your issue is related to #42 which was fixed in the last release. Kindly update the framework to version [2.2.4](https://github.com/kizitonwose/CountryPickerView/releases/tag/2.2.4)
If you are using CocoaPods, you can update only `CountryPickerView` by running the command: `pod update CountryPickerView`

**Comment by zykyan** [comment]
Oh right, I see. Thanks man, in simulator it was starting from uppercase. Thanks alot
